server:
  port: 8081

spring:
  application:
    name: product-api
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:product}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root@123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
    open-in-view: false
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: ${JWT_SECRET:ZmVzdEluZGlhSXRTZXJ2aWNlc1NlY3JldEtleUZvckpXVFRva2VuU2lnbmluZzIwMjY=}
  access-token-expiration-ms: 900000        # 15 minutes
  refresh-token-expiration-ms: 604800000    # 7 days

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.zestindia.productapi: INFO
